### ISSUE TITLE
There's a chest on my head!

### ISSUE THREAD

**Issue by Daft-Freak** [Hexicube/RTRL#3]
![Screenshot from 2013-03-30](https://f.cloud.github.com/assets/3074891/324395/a9e46b20-9ae4-11e2-9de1-f145c309004f.png)

**Comment by Hexicube** [comment]
Steps to re-create?

**Comment by Daft-Freak** [comment]
Started like that, I'm assuming the chest placing doesn't account for being in such an enclosed space.

**Comment by Hexicube** [comment]
Fixed.
